# room_goals.yaml
# frame: map
# 1301~1304: face 6 o'clock (-Y)  -> yaw = -1.5708
# 1305~1308: face 12 o'clock (+Y) -> yaw = +1.5708

goals:
  "home":
    frame_id: "map"
    position: {x: 0.0,  y: 0.0, z: 0.0}
    yaw: -1.5708
    orientation: {x: 0.0, y: 0.0, z: 0.0, w: 1.0}

  "1301":
    frame_id: "map"
    position: {x: 4.3,  y: 3.4, z: 0.0}
    yaw: -1.5708
    orientation: {x: 0.0, y: 0.0, z: -0.7071068, w: 0.7071068}

  "1302":
    frame_id: "map"
    position: {x: 9.1,  y: 3.5, z: 0.0}
    yaw: -1.5708
    orientation: {x: 0.0, y: 0.0, z: -0.7071068, w: 0.7071068}

  "1303":
    frame_id: "map"
    position: {x: 13.9, y: 3.6, z: 0.0}
    yaw: -1.5708
    orientation: {x: 0.0, y: 0.0, z: -0.7071068, w: 0.7071068}

  "1304":
    frame_id: "map"
    position: {x: 18.6, y: 3.7, z: 0.0}
    yaw: -1.5708
    orientation: {x: 0.0, y: 0.0, z: -0.7071068, w: 0.7071068}

  "1305":
    frame_id: "map"
    position: {x: 4.3,  y: 5.7, z: 0.0}
    yaw: 1.5708
    orientation: {x: 0.0, y: 0.0, z: 0.7071068, w: 0.7071068}

  "1306":
    frame_id: "map"
    position: {x: 9.1,  y: 5.8, z: 0.0}
    yaw: 1.5708
    orientation: {x: 0.0, y: 0.0, z: 0.7071068, w: 0.7071068}

  "1307":
    frame_id: "map"
    position: {x: 13.9, y: 5.9, z: 0.0}
    yaw: 1.5708
    orientation: {x: 0.0, y: 0.0, z: 0.7071068, w: 0.7071068}

  "1308":
    frame_id: "map"
    position: {x: 18.6, y: 6.0, z: 0.0}
    yaw: 1.5708
    orientation: {x: 0.0, y: 0.0, z: 0.7071068, w: 0.7071068}
